### ISSUE TITLE
Actually write some code

### ISSUE THREAD

**Issue by mithrandi** [mithrandi/txpasslib#1]
There isn't any actual code in this project yet, we should add some; probably the scope of this issue is to add a basic wrapper around the core passlib KDF functionality.

**Comment by markrwilliams** [comment]
@dstufft suggested we prioritize integrating [CryptContext](https://pythonhosted.org/passlib/lib/passlib.context.html#passlib.context.CryptContext). 

Do we want to wrap it?  Users could then do something like:

```python
context = TxCryptContext(CryptContext(schemes=["sha256_crypt", "ldap_salted_md5"],
                                      sha256_crypt__default_rounds=91234,
                                      ldap_salted_md5__salt_size=16))

someDeferred = context.hash(password)
```

This would be hard to call wrong, but it'd also be hard to maintain (we need to track `CryptContext`'s API).

I can't think of an implementation that would be equivalently easy-to-use.  Thoughts?

**Comment by mithrandi** [comment]
That is basically what I had in mind. I don't think tracking `CryptContext`'s API should be a tremendous hardship, the alternative would mean leaving it up to the user to figure out what needs to be invoked in the thread pool and what doesn't, which is not some place I want to go.

I'm assuming that it's not safe to use the same `CryptContext` object from multiple threads since it is mutable, so we would need some way of copying the context for each worker thread…ah, I just noticed [this](https://pythonhosted.org/passlib/lib/passlib.context.html#passlib.context.CryptContext.to_dict): "…in fact `CryptContext(**myctx.to_dict())` will create an exact copy of `myctx`". So that should work for our purposes.

**Comment by mithrandi** [comment]
Actually, on further inspection, it looks like they do (try) to ensure thread-safety; they even have a unit test that does a bunch of hashing concurrently to try to detect any bugs.
